{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "skillful-mcp.fullname" . }}
  labels:
    {{- include "skillful-mcp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "skillful-mcp.catalog.fullname" . }}
                port:
                  number: {{ .Values.catalog.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "skillful-mcp.webui.fullname" . }}
                port:
                  number: {{ .Values.webui.service.port }}
{{- end -}}
